<?php
use App\Models\Category;
return [
    'title'=>'分类',
    'single'=>'分类',
    'model'=>Category::class,
    //对CRUD权限进行单独控制
    'action_permissions'=>[
        'delete'=>function($model){
            return Auth::user()->hasRole('Founder');
        },
    ],
    'columns'=>[
        'id'=>[
            'title'=>'ID',
        ],
        'name'=>[
            'title'=>'分类名称',
            'sortable'=>false
        ],
        'description'=>[
            'title'=>'描述',
            'sortable'=>false
        ],
        'operation'=>[
            'title'=>'管理',
            'sortable'=>false
        ]
    ],
    'edit_fields'=>[
        'name'=>[
            'title'=>'分类名称',
        ],
        'description'=>[
            'title'=>'分类描述',
            'type'=>'textarea'
        ],
    ],
    'filters'=>[
        'id'=>[
            'title'=>'分类ID'
        ],
        'name'=>[
            'title'=>'分类名称'
        ],
        'description'=>[
            'title'=>'分类描述'
        ],
    ],
    'rules'=>[
        'name'=>'required|max:30|unique:categories'
    ],
    'messages'=>[
        'name.required'=>'分类名称必须填',
        'name.max'=>'分类名称不能超过30个字',
        'name.unique'=>'分类名称已存在'
    ]
];
